/*
 * wio_lite_ai_errno.h
 *
 *  Created on: Jan 16, 2024
 *      Author: cleme
 */

#ifndef BSP_WIO_LITE_AI_WIO_LITE_AI_ERRNO_H_
#define BSP_WIO_LITE_AI_WIO_LITE_AI_ERRNO_H_

/* Common Error codes */
#define BSP_ERROR_NONE 0
#define BSP_ERROR_NO_INIT -1
#define BSP_ERROR_WRONG_PARAM -2
#define BSP_ERROR_BUSY -3
#define BSP_ERROR_PERIPH_FAILURE -4
#define BSP_ERROR_COMPONENT_FAILURE -5
#define BSP_ERROR_UNKNOWN_FAILURE -6
#define BSP_ERROR_UNKNOWN_COMPONENT -7
#define BSP_ERROR_BUS_FAILURE -8
#define BSP_ERROR_CLOCK_FAILURE -9
#define BSP_ERROR_MSP_FAILURE -10
#define BSP_ERROR_FEATURE_NOT_SUPPORTED -11

/* BSP OSPI error codes */
#define BSP_ERROR_OSPI_SUSPENDED -20
#define BSP_ERROR_OSPI_ASSIGN_FAILURE -24
#define BSP_ERROR_OSPI_SETUP_FAILURE -25
#define BSP_ERROR_OSPI_MMP_LOCK_FAILURE -26
#define BSP_ERROR_OSPI_MMP_UNLOCK_FAILURE -27

/* BSP BUS error codes */
#define BSP_ERROR_BUS_TRANSACTION_FAILURE    -100
#define BSP_ERROR_BUS_ARBITRATION_LOSS       -101
#define BSP_ERROR_BUS_ACKNOWLEDGE_FAILURE    -102
#define BSP_ERROR_BUS_PROTOCOL_FAILURE       -103

#define BSP_ERROR_BUS_MODE_FAULT             -104
#define BSP_ERROR_BUS_FRAME_ERROR            -105
#define BSP_ERROR_BUS_CRC_ERROR              -106
#define BSP_ERROR_BUS_DMA_FAILURE            -107

#endif /* BSP_WIO_LITE_AI_WIO_LITE_AI_ERRNO_H_ */
